# Force H2 Database to save items to a local file on your hard disk instead of RAM
spring.datasource.url=jdbc:h2:file:./data/bitesprintdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ensure the database tables update dynamically without wiping out old items
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true